TerrainHousing:
  Prefix: '&8[&aTerrain&eHousing&8]&r '
  Enabled: true
  OverrideProtections: false
  SignText:
    Available:
    - '&2--&a&lAvailable&2--'
    - ''
    - '&2Right Click'
    - '&2to claim'
    Occupied:
    - '&4--&c&lOccupied&4--'
    - '&c&1Occupied by'
    - '&l%player%'
    - '&bIdle: %timer%'
    Resetting:
    - '&c--&0&lResetting&c--'
    - '&4Session expired'
    - '&4Please return'
    - '&4later'
  Location:
    Plain:
      Minimum:
        ==: org.bukkit.Location
        world: world
        x: -97.0
        y: 91.0
        z: 231.0
        pitch: 0.0
        yaw: 0.0
      Maximum:
        ==: org.bukkit.Location
        world: world
        x: -112.0
        y: 107.0
        z: 216.0
        pitch: 0.0
        yaw: 0.0
      Sign:
        ==: org.bukkit.Location
        world: world
        x: -105.0
        y: 92.0
        z: 233.0
        pitch: 0.0
        yaw: 0.0
      Skull:
        ==: org.bukkit.Location
        world: world
        x: -104.0
        y: 93.0
        z: 232.0
        pitch: 0.0
        yaw: 0.0
      Idle: 300
      # Occupied: 991d961c-b6b4-4d49-88e6-01788cf445dc
